version: '3.9'

services:
  backend:
    build:
      context: ./backend/Back
      dockerfile: Dockerfile
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Database=mydb;Username=postgres;Password=mysecretpassword
    depends_on:
      - database
    networks:
      - project-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Mapping the frontend service port to localhost:4200
    networks:
      - project-network

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d 
    networks:
      - project-network

networks:
  project-network:

volumes:
  db-data:
